
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: countcars-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: countcars-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
